name: Pytest tests
on: [push]
jobs:
  get-infos-job:
    runs-on: ubuntu-latest
    name: Get runner infos
    steps:
      - uses: actions/checkout@v3
      - name: get infos
        run: |
          echo "Repo name: ${{ github.repository }}"
          echo "Branch name: ${{ github.ref }}"
          echo "Runner name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }} - ${{ runner.arch }}"
  test-job:
    runs-on: ubuntu-latest
    name: Pytest passing tests
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pytest Action Step
        id: pytest
        uses: paolorechia/fast-pytest-github-action@develop
        with:
          pytest_args: 'test.py'
          requirements_file: 'requirements.txt'