name: Pytest tests
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Pytest passing tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pytest Action Step
        id: pytest
        uses: paolorechia/fast-pytest-github-action@develop
        with:
          pytest_args: 'test.py'
          requirements_file: 'requirements.txt'